/**
 * Language Store - Zustand Store para i18n
 * Reemplaza LanguageContext con mejor performance
 */
import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'es' | 'en' | 'pt';

// Translations dictionary - Exportado para uso en hooks
export const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.events': 'Eventos',
    'nav.contact': 'Contacto',
    'nav.profile': 'Mi Perfil',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.balance': 'Saldo',
    
    // Hero Section
    'hero.title': 'Vive la Experiencia de tus Eventos Favoritos',
    'hero.subtitle': 'Miles de eventos, un solo lugar. Compra tus boletos de forma segura y rápida.',
    'hero.search.placeholder': 'Buscar eventos, artistas, equipos...',
    'hero.search.button': 'Buscar Eventos',
    'hero.search.city': 'Todas las ciudades',
    
    // Categories
    'category.concerts': 'Conciertos',
    'category.sports': 'Deportes',
    'category.theater': 'Teatro',
    'category.family': 'Familia',
    'category.familia': 'Familia',
    
    // Event Card
    'event.from': 'Desde',
    'event.buy': 'Comprar Boletos',
    'event.sold_out': 'Agotado',
    'event.featured': 'Destacado',
    'event.trending': 'Trending',
    'event.last_tickets': 'Últimas entradas',
    
    // Currency
    'currency.preferred': 'Moneda Preferida',
    'currency.select': 'Seleccionar Moneda',
    
    // Language
    'language.select': 'Seleccionar Idioma',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.portuguese': 'Português',
    
    // Balance
    'balance.title': 'Mi Saldo',
    'balance.add': 'Agregar Saldo',
    'balance.total': 'Saldo Total',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    
    // Pages
    'page.events.available': 'Eventos Disponibles',
    'page.events.featured': 'Eventos Destacados',
    'page.events.upcoming': 'Próximos Eventos',
    'page.events.view_all': 'Ver Todos los Eventos',
    'page.organizers.title': '¿Organizas Eventos?',
    'page.organizers.subtitle': 'Transforma tu evento en una experiencia inolvidable. Vende tickets, gestiona asistentes y maximiza tus ingresos con nuestra plataforma profesional.',
    'page.organizers.badge': 'Para Organizadores',
    'page.organizers.create_event': 'Crear mi Primer Evento',
    'page.organizers.how_it_works': 'Ver Cómo Funciona',
    'page.organizers.stats.tickets': 'Tickets Vendidos',
    'page.organizers.stats.events': 'Eventos Exitosos',
    'page.organizers.stats.satisfaction': 'Satisfacción',
    'page.profile.view': 'Ver Mi Perfil',
    'page.profile.explore': 'Explorar Eventos',
    'page.confirmation.back_home': 'Volver al Inicio',
    'page.event.buy_tickets': 'Comprar Tickets',
    
    // Navigation categories
    'nav.category.concerts': 'Conciertos',
    'nav.category.sports': 'Deportes',
    'nav.category.theater': 'Teatro',
    'nav.category.family': 'Familia',
    
    // Categories - Extended
    'category.art': 'Arte',
    'category.comedy': 'Comedia',
    'category.festivals': 'Festivales',
    'category.concert': 'Concierto',
    'category.concierto': 'Concierto',
    'category.festival': 'Festival',
    'category.deportes': 'Deportes',
    'category.teatro': 'Teatro',
    'category.danza': 'Danza',
    'category.comedia': 'Comedia',
    
    // Event Titles (dynamic translations)
    'event.title.1': 'Rock Fest 2025 - Los Mejores Artistas del Rock',
    'event.title.2': 'Festival de Música Electrónica 2025',
    'event.title.3': 'Final de Basketball - Campeonato Nacional',
    'event.title.4': 'El Fantasma de la Ópera - Función Especial',
    'event.title.5': 'Concierto Sinfónico - Beethoven en Vivo',
    'event.title.6': 'Stand Up Comedy Night',
    'event.title.7': 'Fútbol: Clásico Nacional',
    'event.title.8': 'Obra de Teatro: Romeo y Julieta',
    'event.title.9': 'Jazz Night - Leyendas del Jazz',
    'event.title.10': 'Boxeo: Campeonato Mundial de Peso Pesado',
    'event.title.11': 'Ballet Folklórico Internacional',
    'event.title.12': 'Festival Gastronómico Internacional',
    'event.title.13': 'Exposición de Arte Contemporáneo',
    'event.title.14': 'Tenis: ATP Tour Finals',
    'event.title.15': 'Pop Latino Tour 2025',
    'event.title.16': 'Circo del Sol - Alegría',
    'event.title.17': 'Indie Rock Festival USA',
    'event.title.18': 'Musical: El Rey León',
    'event.title.19': 'Reggaeton & Trap Party',
    'event.title.20': 'Lucha Libre - Función Estelar',
    
    // HomePage
    'home.hero.title': 'Todo Empieza con un Sí',
    'home.hero.subtitle': 'Ese momento en que decides salir, vivir, sentir algo diferente.',
    'home.hero.button': 'Ver más',
    'home.section2.title': 'Luces encendidas, la multitud vibra',
    'home.section2.subtitle': 'Tu lugar está reservado... y te espera.',
    'home.section3.title': 'El rugido del estadio, antes del gol',
    'home.section3.subtitle': 'Cada entrada te lleva directo al corazón del juego.',
    'home.section4.title': 'Ríes, lloras, aplaudes.',
    'home.section4.subtitle': 'Porque el arte también se vive desde adentro',
    'home.stats.tickets': 'Tickets Vendidos',
    'home.stats.rating': 'Calificación Promedio',
    'home.categories.title': 'Explora por Categoría',
    'home.categories.subtitle': 'Encuentra eventos que te apasionan',
    'home.upcoming.subtitle': 'No te pierdas estos increíbles eventos',
    'home.featured.subtitle': 'Los eventos más populares del momento',
    'home.events.badge': 'Más de 10,000 eventos disponibles',
    
    // EventsListPage
    'events.hero.title': 'Vive la experiencia de tus eventos favoritos',
    'events.hero.subtitle': 'Miles de eventos, en un solo lugar. Compra tus boletos de forma segura y rápida.',
    'events.search.placeholder': 'Buscar eventos, artistas, equipos...',
    'events.search.cities': 'Todas las ciudades',
    'events.search.button': 'Buscar Eventos',
    'events.categories.concerts': 'Conciertos',
    'events.categories.sports': 'Deportes',
    'events.categories.theater': 'Teatro',
    'events.categories.festivals': 'Festivales',
    'events.stats.users': 'Usuarios Activos',
    'events.stats.tickets': 'Boletos Vendidos',
    'events.stats.events': 'Eventos Realizados',
    'events.stats.rating': 'Calificación Promedio',
    'events.featured.title': 'Eventos Destacados',
    'events.upcoming.title': 'Próximos eventos',
    'events.upcoming.subtitle': 'No te pierdas estos increíbles eventos',
    'events.button.buy': 'Comprar boletos',
    'events.button.viewAll': 'Ver todos los eventos',
    'events.category.eventsCount': 'eventos',
    'events.card.from': 'Desde',
    'events.card.lastTickets': 'Últimos',
    'events.card.upcoming': 'Próximos',
    'events.card.future': 'Futuros',
    'events.card.current': 'Actuales',
    'events.card.featured': 'Imperdible',
    'events.card.featuredAlt': 'Destacado',
    'events.card.recommended': 'Recomendado',
    'events.card.trending': 'Tendencia',
    'events.card.soldOut': 'Agotado',
    
    // AllEventsPage
    'allevents.back': 'Volver',
    'allevents.title': 'Todos los Eventos',
    'allevents.filters': 'Filtros',
    'allevents.search.placeholder': 'Buscar eventos...',
    'allevents.categories.all': 'Todos',
    'allevents.sort.date': 'Fecha',
    'allevents.sort.priceAsc': 'Precio: Menor a Mayor',
    'allevents.sort.priceDesc': 'Precio: Mayor a Menor',
    'allevents.sort.popularity': 'Popularidad',
    'allevents.sort.name': 'Nombre',
    'allevents.sort.by': 'Ordenar por',
    'allevents.filters.advanced': 'Filtros Avanzados',
    'allevents.filters.cities': 'Ciudades',
    'allevents.filters.price': 'Rango de Precio',
    'allevents.filters.featured': 'Solo Destacados',
    'allevents.filters.trending': 'Solo Tendencias',
    'allevents.filters.lastTickets': 'Últimos Boletos',
    'allevents.pagination.previous': 'Anterior',
    'allevents.pagination.next': 'Siguiente',
    'allevents.noResults': 'No se encontraron eventos',
    
    // Footer
    'footer.description': 'La mejor plataforma para encontrar y comprar tickets de tus eventos favoritos.',
    'footer.events': 'Eventos',
    'footer.help': 'Ayuda',
    'footer.help.center': 'Centro de Ayuda',
    'footer.help.contact': 'Contacto',
    'footer.help.refund': 'Política de Reembolso',
    'footer.help.terms': 'Términos y Condiciones',
    'footer.help.privacy': 'Privacidad',
    'footer.organizers': 'Organizadores',
    'footer.organizers.sell': 'Vende Tickets',
    'footer.organizers.create': 'Crea un Evento',
    'footer.organizers.resources': 'Recursos',
    'footer.organizers.pricing': 'Pricing',
    'footer.copyright': 'Todos los derechos reservados.',
    
    // Event Detail
    'event.detail.back': 'Volver',
    'event.detail.share': 'Compartir',
    'event.detail.featured': 'Destacado',
    'event.detail.date': 'Fecha',
    'event.detail.time': 'Hora',
    'event.detail.location': 'Ubicación',
    'event.detail.description': 'Descripción del Evento',
    'event.detail.venue': 'Información del Venue',
    'event.detail.venueCapacity': 'Capacidad',
    'event.detail.venueParking': 'Estacionamiento',
    'event.detail.venueAccessibility': 'Accesibilidad',
    'event.detail.reviews': 'Reseñas',
    'event.detail.tickets': 'Selecciona tus Tickets',
    'event.detail.ticketsSubtitle': 'Elige el tipo de entrada que prefieras',
    'event.detail.ticketAvailable': 'Disponible',
    'event.detail.buyTickets': 'Comprar Tickets',
    'event.detail.selectTicket': 'Selecciona un tipo de ticket primero',
    'event.detail.offer': '¡Oferta Especial!',
    'event.detail.offerText': 'Compra 2 o más tickets y obtén un 10% de descuento',
    'event.detail.discount': 'Compra 3 tickets y obtén 15% de descuento',
    'event.detail.general': 'General',
    'event.detail.vip': 'VIP',
    'event.detail.palco': 'Palco Premium',
    'event.detail.standard_access': 'Acceso estándar al evento',
    'event.detail.preferential_seats': 'Asientos preferenciales',
    'event.detail.exclusive_experience': 'Experiencia exclusiva',
    'event.detail.general_access': 'Acceso general',
    'event.detail.parking_included': 'Estacionamiento incluido',
    'event.detail.vip_access': 'Acceso a zona VIP',
    'event.detail.meet_greet': 'Meet & Greet',
    'event.detail.private_box': 'Palco privado (4 personas)',
    'event.detail.waiter_service': 'Servicio de mesero',
    'event.detail.drinks_included': 'Bebidas incluidas',
    
    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.back': 'Volver',
    'checkout.event_details': 'Detalles del Evento',
    'checkout.ticket_type': 'Tipo de Boleto',
    'checkout.quantity': 'Cantidad de Boletos',
    'checkout.max_tickets': 'Máximo 10 boletos por compra',
    'checkout.buyer_info': 'Información del Comprador',
    'checkout.buyer_info_desc': 'Necesitamos esta información para procesar tu compra y enviarte los boletos',
    'checkout.full_name': 'Nombre Completo',
    'checkout.email': 'Correo Electrónico',
    'checkout.phone': 'Teléfono (Opcional)',
    'checkout.attendees': 'Información de Asistentes',
    'checkout.attendees_desc': 'Ingresa el nombre de cada persona que asistirá al evento',
    'checkout.attendee_name': 'Nombre del Asistente',
    'checkout.special_requests': 'Solicitudes Especiales',
    'checkout.special_requests_placeholder': 'Alergias, necesidades especiales, etc.',
    'checkout.purchase_summary': 'Resumen de Compra',
    'checkout.subtotal': 'Subtotal',
    'checkout.service_fee': 'Cargo por Servicio',
    'checkout.total': 'Total',
    'checkout.pay': 'Pagar',
    'checkout.processing': 'Procesando...',
    'checkout.complete_form': 'Completa el formulario arriba',
    'checkout.secure_payment': 'Pago seguro con tu saldo interno',
    'checkout.insufficient_balance': 'Saldo Insuficiente',
    'checkout.insufficient_balance_desc': 'Necesitas ${amount} MXN más para completar esta compra',
    'checkout.add_balance': 'Agregar Saldo',
    'checkout.add_balance_title': 'Agregar Saldo a tu Cuenta',
    'checkout.add_balance_desc': 'Selecciona el monto que deseas agregar',
    'checkout.amount': 'Monto',
    'checkout.add': 'Agregar',
    'checkout.adding': 'Agregando...',
    'checkout.error.required_fields': 'Por favor completa todos los campos obligatorios',
    'checkout.error.invalid_email': 'Por favor ingresa un email válido',
    'checkout.error.attendees': 'Por favor ingresa el nombre de todos los asistentes',
    'checkout.error.complete_steps': 'Por favor completa todos los pasos antes de realizar el pago',
    'checkout.error.buyer_info': 'Por favor completa la información del comprador',
    
    // Login
    'login.welcome': 'Bienvenido a TicketMaster',
    'login.subtitle': 'Ingresa o crea tu cuenta para continuar',
    'login.password': 'Contraseña',
    'login.magic_link': 'Magic Link',
    'login.signup': 'Registrarse',
    'login.passwordless': 'Ingreso sin contraseña',
    'login.passwordless_desc': 'Recibe un enlace mágico en tu email para acceder instantáneamente',
    'login.email': 'Correo Electrónico',
    'login.send_link': 'Enviar Enlace Mágico ✨',
    'login.sending': 'Enviando...',
    'login.link_sent': '¡Enlace Mágico Enviado! 📧',
    'login.link_sent_desc': 'Hemos enviado un enlace de acceso a',
    'login.check_inbox': 'Revisa tu bandeja de entrada y haz clic en el enlace para ingresar automáticamente',
    'login.send_another': 'Enviar otro enlace',
    'login.forgot_password': '¿Olvidaste tu contraseña?',
    'login.sign_in': 'Iniciar Sesión',
    'login.signing_in': 'Ingresando...',
    'login.create_account': 'Crear Cuenta',
    'login.creating': 'Creando...',
    'login.error.signin': 'Error al iniciar sesión',
    'login.error.signup': 'Error al crear cuenta',
    'login.error.magic_link': 'Error al enviar el enlace mágico',
    'login.error.reset': 'Error al enviar el enlace de recuperación',
    
    // Profile
    'profile.back': 'Volver al inicio',
    'profile.my_tickets': 'Mis Tickets',
    'profile.my_tickets_page': 'Mis Boletas',
    'profile.my_tickets_desc': 'Ver y descargar todas tus boletas de eventos',
    'profile.view_my_tickets': 'Ver Mis Boletas',
    'profile.transactions': 'Historial de Transacciones',
    'profile.loading_tickets': 'Cargando tickets...',
    'profile.no_tickets': 'No tienes tickets',
    'profile.no_tickets_desc': 'Explora eventos y compra tus primeros tickets',
    'profile.seat': 'Asiento',
    'profile.view_qr': 'Ver QR',
    'profile.transfer': 'Transferir',
    'profile.transferred': 'Recibido por transferencia',
    'profile.no_transactions': 'No hay transacciones aún',
    'profile.used_tickets': 'Tickets Usados',
    'profile.used_on': 'Usado el',
    'profile.completed': 'Completado',
    'profile.transfer_ticket': 'Transferir Ticket',
    'profile.transfer_desc': 'Ingresa el correo electrónico de la persona a quien deseas transferir este ticket',
    'profile.recipient_email': 'Correo del Destinatario',
    'profile.transferring': 'Transfiriendo...',
    'profile.important': 'Importante',
    'profile.transfer_warning': 'Una vez transferido, no podrás recuperar este ticket. La persona que lo reciba será la nueva propietaria.',
    'profile.verification_code': 'Código de verificación generado',
    'profile.close': 'Cerrar',
    
    // Wallet
    'wallet.title': 'Mi Billetera',
    'wallet.total_balance': 'Saldo Total',
    'wallet.multi_currency': 'Saldo en Diferentes Monedas',
    'wallet.recent_transactions': 'Últimas Transacciones',
    'wallet.add_balance': 'Agregar Saldo',
    'wallet.info': 'Información',
    'wallet.info_desc': 'Tu saldo está protegido y disponible en todo momento para comprar tickets.',
    
    // Cart
    'cart.title': 'Mi Carrito',
    'cart.empty': 'Carrito vacío',
    'cart.empty_title': 'Tu carrito está vacío',
    'cart.empty_desc': 'Agrega tickets de eventos increíbles a tu carrito para comenzar.',
    'cart.item': 'artículo',
    'cart.items': 'artículos',
    'cart.quantity': 'Cantidad',
    'cart.each': 'cada uno',
    'cart.summary': 'Resumen del Pedido',
    'cart.subtotal': 'Subtotal',
    'cart.service_fee': 'Cargo por Servicio',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al Pago',
    'cart.clear': 'Limpiar Carrito',
    'cart.browse_events': 'Explorar Eventos',
    'cart.login_required': 'Inicia sesión para ver tu carrito',
    'cart.login_required_desc': 'Necesitas iniciar sesión para agregar tickets a tu carrito.',
    'cart.secure_checkout': 'Pago seguro y protegido',
    
    // Confirmation
    'confirmation.success': '¡Compra Exitosa!',
    'confirmation.success_desc': 'Tu {count} ticket{plural} ha{plural_verb} sido comprado{plural} exitosamente',
    'confirmation.purchase_summary': 'Resumen de Compra',
    'confirmation.total_paid': 'Total Pagado',
    'confirmation.internal_balance': 'Saldo Interno',
    'confirmation.remaining_balance': 'Saldo Restante',
    'confirmation.your_tickets': 'Tus Tickets',
    'confirmation.your_ticket': 'Tu Ticket',
    'confirmation.ticket_info': 'Los tickets están disponibles en la sección "Mis Tickets"',
    'confirmation.view_tickets': 'Ver Mis Tickets',
    
    // Events List
    'events.back': 'Volver',
    'events.title': 'Explorar Eventos',
    'events.date': 'Fecha',
    'events.price_low': 'Precio: Menor a Mayor',
    'events.price_high': 'Precio: Mayor a Menor',
    'events.name': 'Nombre A-Z',
    'events.price_range': 'Rango de Precio',
    'events.special_types': 'Tipos Especiales',
    'events.featured': 'Eventos Destacados',
    'events.trending': 'Trending',
    'events.trending_desc': 'Los más populares ahora',
    'events.last_tickets': 'Últimos Boletos',
    'events.no_results': 'No se encontraron eventos',
    'events.no_results_desc': 'Intenta ajustar tus filtros de búsqueda para obtener más resultados',
    
    // Footer
    'footer.description': 'La mejor plataforma para encontrar y comprar tickets de tus eventos favoritos.',
    'footer.events': 'Eventos',
    'footer.sell_tickets': 'Vende Tickets',
    'footer.create_event': 'Crea un Evento',
    
    // Common UI
    'ui.search': 'Buscar Eventos',
    'ui.trending': 'Tendencia',
    'ui.last_tickets': 'Últimos',
    'ui.featured': 'Destacado',
    'ui.sold_out': 'AGOTADO',
    'ui.from': 'Desde',
    'ui.mis_tickets': 'Mis Tickets',
    'ui.ingresar': 'Ingresar',
    
    // Contact Page
    'contact.page.title': 'Contacto',
    'contact.page.description': 'Ponte en contacto con nosotros. Estamos aquí para ayudarte.',
    'contact.hero.title': 'Estamos Aquí para Ayudarte',
    'contact.hero.subtitle': '¿Tienes preguntas, sugerencias o necesitas ayuda? Nuestro equipo está listo para atenderte.',
    'contact.info.email': 'Correo Electrónico',
    'contact.info.phone': 'Teléfono',
    'contact.info.location': 'Ubicación',
    'contact.info.address': 'Av. Principal 123, Ciudad, País',
    'contact.info.hours': 'Horario de Atención',
    'contact.info.hours.weekdays': 'Lun - Vie: 9:00 AM - 6:00 PM',
    'contact.info.hours.weekends': 'Sáb - Dom: 10:00 AM - 4:00 PM',
    'contact.faq.title': '¿Necesitas Ayuda Rápida?',
    'contact.faq.description': 'Consulta nuestras preguntas frecuentes para obtener respuestas inmediatas.',
    'contact.faq.button': 'Ver Preguntas Frecuentes',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.subtitle': 'Completa el formulario y nos pondremos en contacto contigo lo antes posible.',
    'contact.form.name': 'Nombre Completo',
    'contact.form.name.placeholder': 'Tu nombre',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.email.placeholder': 'tu@email.com',
    'contact.form.phone': 'Teléfono',
    'contact.form.phone.placeholder': '+1 (234) 567-890',
    'contact.form.subject': 'Asunto',
    'contact.form.subject.placeholder': '¿En qué podemos ayudarte?',
    'contact.form.message': 'Mensaje',
    'contact.form.message.placeholder': 'Escribe tu mensaje aquí...',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.required': '* Campos obligatorios',
    'contact.form.success.title': '¡Mensaje Enviado!',
    'contact.form.success.message': 'Gracias por contactarnos. Te responderemos pronto.',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.events': 'Events',
    'nav.contact': 'Contact',
    'nav.profile': 'My Profile',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    'nav.balance': 'Balance',
    
    // Hero Section
    'hero.title': 'Experience Your Favorite Events',
    'hero.subtitle': 'Thousands of events, one place. Buy your tickets securely and quickly.',
    'hero.search.placeholder': 'Search events, artists, teams...',
    'hero.search.button': 'Search Events',
    'hero.search.city': 'All cities',
    
    // Categories
    'category.concerts': 'Concerts',
    'category.sports': 'Sports',
    'category.theater': 'Theater',
    'category.family': 'Family',
    
    // Event Card
    'event.from': 'From',
    'event.buy': 'Buy Tickets',
    'event.sold_out': 'Sold Out',
    'event.featured': 'Featured',
    'event.trending': 'Trending',
    'event.last_tickets': 'Last tickets',
    
    // Currency
    'currency.preferred': 'Preferred Currency',
    'currency.select': 'Select Currency',
    
    // Language
    'language.select': 'Select Language',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.portuguese': 'Português',
    
    // Balance
    'balance.title': 'My Balance',
    'balance.add': 'Add Balance',
    'balance.total': 'Total Balance',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    
    // Pages
    'page.events.available': 'Available Events',
    'page.events.featured': 'Featured Events',
    'page.events.upcoming': 'Upcoming Events',
    'page.events.view_all': 'View All Events',
    'page.organizers.title': 'Do You Organize Events?',
    'page.organizers.subtitle': 'Transform your event into an unforgettable experience. Sell tickets, manage attendees and maximize your revenue with our professional platform.',
    'page.organizers.badge': 'For Organizers',
    'page.organizers.create_event': 'Create My First Event',
    'page.organizers.how_it_works': 'See How It Works',
    'page.organizers.stats.tickets': 'Tickets Sold',
    'page.organizers.stats.events': 'Successful Events',
    'page.organizers.stats.satisfaction': 'Satisfaction',
    'page.profile.view': 'View My Profile',
    'page.profile.explore': 'Explore Events',
    'page.confirmation.back_home': 'Back to Home',
    'page.event.buy_tickets': 'Buy Tickets',
    
    // Navigation categories
    'nav.category.concerts': 'Concerts',
    'nav.category.sports': 'Sports',
    'nav.category.theater': 'Theater',
    'nav.category.family': 'Family',
    
    // Categories - Extended
    'category.art': 'Art',
    'category.comedy': 'Comedy',
    'category.festivals': 'Festivals',
    'category.concert': 'Concert',
    'category.concierto': 'Concert',
    'category.festival': 'Festival',
    'category.deportes': 'Sports',
    'category.teatro': 'Theater',
    'category.danza': 'Dance',
    'category.comedia': 'Comedy',
    'category.familia': 'Family',
    
    // Event Titles (dynamic translations)
    'event.title.1': 'Rock Fest 2025 - The Best Rock Artists',
    'event.title.2': 'Electronic Music Festival 2025',
    'event.title.3': 'Basketball Finals - National Championship',
    'event.title.4': 'The Phantom of the Opera - Special Show',
    'event.title.5': 'Symphonic Concert - Beethoven Live',
    'event.title.6': 'Stand Up Comedy Night',
    'event.title.7': 'Soccer: National Classic',
    'event.title.8': 'Theater Play: Romeo and Juliet',
    'event.title.9': 'Jazz Night - Jazz Legends',
    'event.title.10': 'Boxing: Heavyweight World Championship',
    'event.title.11': 'International Folkloric Ballet',
    'event.title.12': 'International Food Festival',
    'event.title.13': 'Contemporary Art Exhibition',
    'event.title.14': 'Tennis: ATP Tour Finals',
    'event.title.15': 'Latin Pop Tour 2025',
    'event.title.16': 'Cirque du Soleil - Alegría',
    'event.title.17': 'Indie Rock Festival USA',
    'event.title.18': 'Musical: The Lion King',
    'event.title.19': 'Reggaeton & Trap Party',
    'event.title.20': 'Wrestling - Main Event',
    
    // HomePage
    'home.hero.title': 'It All Starts with a Yes',
    'home.hero.subtitle': 'That moment when you decide to go out, live, feel something different.',
    'home.hero.button': 'Learn More',
    'home.section2.title': 'Lights on, the crowd vibrates',
    'home.section2.subtitle': 'Your seat is reserved... and waiting for you.',
    'home.section3.title': 'The roar of the stadium, before the goal',
    'home.section3.subtitle': 'Every ticket takes you straight to the heart of the game.',
    'home.section4.title': 'You laugh, you cry, you applaud.',
    'home.section4.subtitle': 'Because art is also lived from within',
    'home.stats.tickets': 'Tickets Sold',
    'home.stats.rating': 'Average Rating',
    'home.categories.title': 'Explore by Category',
    'home.categories.subtitle': 'Find events that excite you',
    'home.upcoming.subtitle': 'Don\'t miss these amazing events',
    'home.featured.subtitle': 'The most popular events right now',
    'home.events.badge': 'More than 10,000 events available',
    
    // EventsListPage
    'events.hero.title': 'Live the experience of your favorite events',
    'events.hero.subtitle': 'Thousands of events, all in one place. Buy your tickets safely and quickly.',
    'events.search.placeholder': 'Search events, artists, teams...',
    'events.search.cities': 'All cities',
    'events.search.button': 'Search Events',
    'events.categories.concerts': 'Concerts',
    'events.categories.sports': 'Sports',
    'events.categories.theater': 'Theater',
    'events.categories.festivals': 'Festivals',
    'events.stats.users': 'Active Users',
    'events.stats.tickets': 'Tickets Sold',
    'events.stats.events': 'Events Held',
    'events.stats.rating': 'Average Rating',
    'events.featured.title': 'Featured Events',
    'events.upcoming.title': 'Upcoming Events',
    'events.upcoming.subtitle': 'Don\'t miss these amazing events',
    'events.button.buy': 'Buy Tickets',
    'events.button.viewAll': 'View All Events',
    'events.category.eventsCount': 'events',
    'events.card.from': 'From',
    'events.card.lastTickets': 'Last',
    'events.card.upcoming': 'Upcoming',
    'events.card.future': 'Future',
    'events.card.current': 'Current',
    'events.card.featured': 'Must See',
    'events.card.featuredAlt': 'Featured',
    'events.card.recommended': 'Recommended',
    'events.card.trending': 'Trending',
    'events.card.soldOut': 'Sold Out',
    
    // AllEventsPage
    'allevents.back': 'Back',
    'allevents.title': 'All Events',
    'allevents.filters': 'Filters',
    'allevents.search.placeholder': 'Search events...',
    'allevents.categories.all': 'All',
    'allevents.sort.date': 'Date',
    'allevents.sort.priceAsc': 'Price: Low to High',
    'allevents.sort.priceDesc': 'Price: High to Low',
    'allevents.sort.popularity': 'Popularity',
    'allevents.sort.name': 'Name',
    'allevents.sort.by': 'Sort by',
    'allevents.filters.advanced': 'Advanced Filters',
    'allevents.filters.cities': 'Cities',
    'allevents.filters.price': 'Price Range',
    'allevents.filters.featured': 'Featured Only',
    'allevents.filters.trending': 'Trending Only',
    'allevents.filters.lastTickets': 'Last Tickets',
    'allevents.pagination.previous': 'Previous',
    'allevents.pagination.next': 'Next',
    'allevents.noResults': 'No events found',
    
    // Footer
    'footer.description': 'The best platform to find and buy tickets for your favorite events.',
    'footer.events': 'Events',
    'footer.help': 'Help',
    'footer.help.center': 'Help Center',
    'footer.help.contact': 'Contact',
    'footer.help.refund': 'Refund Policy',
    'footer.help.terms': 'Terms and Conditions',
    'footer.help.privacy': 'Privacy',
    'footer.organizers': 'Organizers',
    'footer.organizers.sell': 'Sell Tickets',
    'footer.organizers.create': 'Create an Event',
    'footer.organizers.resources': 'Resources',
    'footer.organizers.pricing': 'Pricing',
    'footer.copyright': 'All rights reserved.',
    
    // Event Detail
    'event.detail.back': 'Back',
    'event.detail.share': 'Share',
    'event.detail.featured': 'Featured',
    'event.detail.date': 'Date',
    'event.detail.time': 'Time',
    'event.detail.location': 'Location',
    'event.detail.description': 'Event Description',
    'event.detail.venue': 'Venue Information',
    'event.detail.venueCapacity': 'Capacity',
    'event.detail.venueParking': 'Parking',
    'event.detail.venueAccessibility': 'Accessibility',
    'event.detail.reviews': 'Reviews',
    'event.detail.tickets': 'Select Your Tickets',
    'event.detail.ticketsSubtitle': 'Choose your preferred ticket type',
    'event.detail.ticketAvailable': 'Available',
    'event.detail.buyTickets': 'Buy Tickets',
    'event.detail.selectTicket': 'Select a ticket type first',
    'event.detail.offer': 'Special Offer!',
    'event.detail.offerText': 'Buy 2 or more tickets and get 10% off',
    'event.detail.discount': 'Buy 3 tickets and get 15% discount',
    'event.detail.general': 'General',
    'event.detail.vip': 'VIP',
    'event.detail.palco': 'Premium Box',
    'event.detail.standard_access': 'Standard event access',
    'event.detail.preferential_seats': 'Preferential seats',
    'event.detail.exclusive_experience': 'Exclusive experience',
    'event.detail.general_access': 'General access',
    'event.detail.parking_included': 'Parking included',
    'event.detail.vip_access': 'VIP zone access',
    'event.detail.meet_greet': 'Meet & Greet',
    'event.detail.private_box': 'Private box (4 people)',
    'event.detail.waiter_service': 'Waiter service',
    'event.detail.drinks_included': 'Drinks included',
    
    // Checkout
    'checkout.title': 'Complete Purchase',
    'checkout.back': 'Back',
    'checkout.event_details': 'Event Details',
    'checkout.ticket_type': 'Ticket Type',
    'checkout.quantity': 'Number of Tickets',
    'checkout.max_tickets': 'Maximum 10 tickets per purchase',
    'checkout.buyer_info': 'Buyer Information',
    'checkout.buyer_info_desc': 'We need this information to process your purchase and send you the tickets',
    'checkout.full_name': 'Full Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone (Optional)',
    'checkout.attendees': 'Attendee Information',
    'checkout.attendees_desc': 'Enter the name of each person who will attend the event',
    'checkout.attendee_name': 'Attendee Name',
    'checkout.special_requests': 'Special Requests',
    'checkout.special_requests_placeholder': 'Allergies, special needs, etc.',
    'checkout.purchase_summary': 'Purchase Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.service_fee': 'Service Fee',
    'checkout.total': 'Total',
    'checkout.pay': 'Pay',
    'checkout.processing': 'Processing...',
    'checkout.complete_form': 'Complete the form above',
    'checkout.secure_payment': 'Secure payment with your internal balance',
    'checkout.insufficient_balance': 'Insufficient Balance',
    'checkout.insufficient_balance_desc': 'You need ${amount} MXN more to complete this purchase',
    'checkout.add_balance': 'Add Balance',
    'checkout.add_balance_title': 'Add Balance to Your Account',
    'checkout.add_balance_desc': 'Select the amount you want to add',
    'checkout.amount': 'Amount',
    'checkout.add': 'Add',
    'checkout.adding': 'Adding...',
    'checkout.error.required_fields': 'Please complete all required fields',
    'checkout.error.invalid_email': 'Please enter a valid email',
    'checkout.error.attendees': 'Please enter the name of all attendees',
    'checkout.error.complete_steps': 'Please complete all steps before making payment',
    'checkout.error.buyer_info': 'Please complete buyer information',
    
    // Login
    'login.welcome': 'Welcome to TicketMaster',
    'login.subtitle': 'Sign in or create your account to continue',
    'login.password': 'Password',
    'login.magic_link': 'Magic Link',
    'login.signup': 'Sign Up',
    'login.passwordless': 'Passwordless login',
    'login.passwordless_desc': 'Receive a magic link in your email to access instantly',
    'login.email': 'Email',
    'login.send_link': 'Send Magic Link ✨',
    'login.sending': 'Sending...',
    'login.link_sent': 'Magic Link Sent! 📧',
    'login.link_sent_desc': 'We have sent an access link to',
    'login.check_inbox': 'Check your inbox and click the link to log in automatically',
    'login.send_another': 'Send another link',
    'login.forgot_password': 'Forgot your password?',
    'login.sign_in': 'Sign In',
    'login.signing_in': 'Signing in...',
    'login.create_account': 'Create Account',
    'login.creating': 'Creating...',
    'login.error.signin': 'Error signing in',
    'login.error.signup': 'Error creating account',
    'login.error.magic_link': 'Error sending magic link',
    'login.error.reset': 'Error sending recovery link',
    
    // Profile
    'profile.back': 'Back to home',
    'profile.my_tickets': 'My Tickets',
    'profile.my_tickets_page': 'My Tickets',
    'profile.my_tickets_desc': 'View and download all your event tickets',
    'profile.view_my_tickets': 'View My Tickets',
    'profile.transactions': 'Transaction History',
    'profile.loading_tickets': 'Loading tickets...',
    'profile.no_tickets': 'You don\'t have tickets',
    'profile.no_tickets_desc': 'Explore events and buy your first tickets',
    'profile.seat': 'Seat',
    'profile.view_qr': 'View QR',
    'profile.transfer': 'Transfer',
    'profile.transferred': 'Received by transfer',
    'profile.no_transactions': 'No transactions yet',
    'profile.used_tickets': 'Used Tickets',
    'profile.used_on': 'Used on',
    'profile.completed': 'Completed',
    'profile.transfer_ticket': 'Transfer Ticket',
    'profile.transfer_desc': 'Enter the email address of the person you want to transfer this ticket to',
    'profile.recipient_email': 'Recipient Email',
    'profile.transferring': 'Transferring...',
    'profile.important': 'Important',
    'profile.transfer_warning': 'Once transferred, you cannot recover this ticket. The person who receives it will be the new owner.',
    'profile.verification_code': 'Verification code generated',
    'profile.close': 'Close',
    
    // Wallet
    'wallet.title': 'My Wallet',
    'wallet.total_balance': 'Total Balance',
    'wallet.multi_currency': 'Balance in Different Currencies',
    'wallet.recent_transactions': 'Recent Transactions',
    'wallet.add_balance': 'Add Balance',
    'wallet.info': 'Information',
    'wallet.info_desc': 'Your balance is protected and available at all times to purchase tickets.',
    
    // Cart
    'cart.title': 'My Cart',
    'cart.empty': 'Cart is empty',
    'cart.empty_title': 'Your cart is empty',
    'cart.empty_desc': 'Add tickets to amazing events to your cart to get started.',
    'cart.item': 'item',
    'cart.items': 'items',
    'cart.quantity': 'Quantity',
    'cart.each': 'each',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.service_fee': 'Service Fee',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.clear': 'Clear Cart',
    'cart.browse_events': 'Browse Events',
    'cart.login_required': 'Sign in to view your cart',
    'cart.login_required_desc': 'You need to sign in to add tickets to your cart.',
    'cart.secure_checkout': 'Secure and protected payment',
    
    // Confirmation
    'confirmation.success': 'Successful Purchase!',
    'confirmation.success_desc': 'Your {count} ticket{plural} ha{plural_verb} been purchased successfully',
    'confirmation.purchase_summary': 'Purchase Summary',
    'confirmation.total_paid': 'Total Paid',
    'confirmation.internal_balance': 'Internal Balance',
    'confirmation.remaining_balance': 'Remaining Balance',
    'confirmation.your_tickets': 'Your Tickets',
    'confirmation.your_ticket': 'Your Ticket',
    'confirmation.ticket_info': 'Tickets are available in the "My Tickets" section',
    'confirmation.view_tickets': 'View My Tickets',
    
    // Events List
    'events.back': 'Back',
    'events.title': 'Explore Events',
    'events.date': 'Date',
    'events.price_low': 'Price: Low to High',
    'events.price_high': 'Price: High to Low',
    'events.name': 'Name A-Z',
    'events.price_range': 'Price Range',
    'events.special_types': 'Special Types',
    'events.featured': 'Featured Events',
    'events.trending': 'Trending',
    'events.trending_desc': 'Most popular now',
    'events.last_tickets': 'Last Tickets',
    'events.no_results': 'No events found',
    'events.no_results_desc': 'Try adjusting your search filters to get more results',
    
    // Footer
    'footer.description': 'The best platform to find and buy tickets for your favorite events.',
    'footer.events': 'Events',
    'footer.sell_tickets': 'Sell Tickets',
    'footer.create_event': 'Create an Event',
    
    // Common UI
    'ui.search': 'Search Events',
    'ui.trending': 'Trending',
    'ui.last_tickets': 'Last',
    'ui.featured': 'Featured',
    'ui.sold_out': 'SOLD OUT',
    'ui.from': 'From',
    'ui.mis_tickets': 'My Tickets',
    'ui.ingresar': 'Sign In',
    
    // Contact Page
    'contact.page.title': 'Contact',
    'contact.page.description': 'Get in touch with us. We\'re here to help.',
    'contact.hero.title': 'We\'re Here to Help',
    'contact.hero.subtitle': 'Have questions, suggestions or need assistance? Our team is ready to assist you.',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.location': 'Location',
    'contact.info.address': '123 Main Avenue, City, Country',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours.weekdays': 'Mon - Fri: 9:00 AM - 6:00 PM',
    'contact.info.hours.weekends': 'Sat - Sun: 10:00 AM - 4:00 PM',
    'contact.faq.title': 'Need Quick Help?',
    'contact.faq.description': 'Check our frequently asked questions for immediate answers.',
    'contact.faq.button': 'View FAQs',
    'contact.form.title': 'Send Us a Message',
    'contact.form.subtitle': 'Fill out the form and we\'ll get back to you as soon as possible.',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'you@email.com',
    'contact.form.phone': 'Phone',
    'contact.form.phone.placeholder': '+1 (234) 567-890',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'How can we help?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Write your message here...',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.required': '* Required fields',
    'contact.form.success.title': 'Message Sent!',
    'contact.form.success.message': 'Thanks for contacting us. We\'ll respond soon.',
  },
  
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.events': 'Eventos',
    'nav.contact': 'Contato',
    'nav.profile': 'Meu Perfil',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',
    'nav.balance': 'Saldo',
    
    // Hero Section
    'hero.title': 'Viva a Experiência dos Seus Eventos Favoritos',
    'hero.subtitle': 'Milhares de eventos, um só lugar. Compre seus ingressos com segurança e rapidez.',
    'hero.search.placeholder': 'Pesquisar eventos, artistas, times...',
    'hero.search.button': 'Pesquisar Eventos',
    'hero.search.city': 'Todas as cidades',
    
    // Categories
    'category.concerts': 'Shows',
    'category.sports': 'Esportes',
    'category.theater': 'Teatro',
    'category.family': 'Família',
    'category.familia': 'Família',
    
    // Event Card
    'event.from': 'A partir de',
    'event.buy': 'Comprar Ingressos',
    'event.sold_out': 'Esgotado',
    'event.featured': 'Destaque',
    'event.trending': 'Em alta',
    'event.last_tickets': 'Últimos ingressos',
    
    // Currency
    'currency.preferred': 'Moeda Preferida',
    'currency.select': 'Selecionar Moeda',
    
    // Language
    'language.select': 'Selecionar Idioma',
    'language.spanish': 'Español',
    'language.english': 'English',
    'language.portuguese': 'Português',
    
    // Balance
    'balance.title': 'Meu Saldo',
    'balance.add': 'Adicionar Saldo',
    'balance.total': 'Saldo Total',
    
    // Common
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    
    // Pages
    'page.events.available': 'Eventos Disponíveis',
    'page.events.featured': 'Eventos em Destaque',
    'page.events.upcoming': 'Próximos Eventos',
    'page.events.view_all': 'Ver Todos os Eventos',
    'page.organizers.title': 'Você Organiza Eventos?',
    'page.organizers.subtitle': 'Transforme seu evento em uma experiência inesquecível. Venda ingressos, gerencie participantes e maximize sua receita com nossa plataforma profissional.',
    'page.organizers.badge': 'Para Organizadores',
    'page.organizers.create_event': 'Criar Meu Primeiro Evento',
    'page.organizers.how_it_works': 'Ver Como Funciona',
    'page.organizers.stats.tickets': 'Ingressos Vendidos',
    'page.organizers.stats.events': 'Eventos Bem-sucedidos',
    'page.organizers.stats.satisfaction': 'Satisfação',
    'page.profile.view': 'Ver Meu Perfil',
    'page.profile.explore': 'Explorar Eventos',
    'page.confirmation.back_home': 'Voltar ao Início',
    'page.event.buy_tickets': 'Comprar Ingressos',
    
    // Navigation categories
    'nav.category.concerts': 'Shows',
    'nav.category.sports': 'Esportes',
    'nav.category.theater': 'Teatro',
    'nav.category.family': 'Família',
    
    // Categories - Extended
    'category.art': 'Arte',
    'category.comedy': 'Comédia',
    'category.festivals': 'Festivais',
    'category.concert': 'Show',
    'category.concierto': 'Show',
    'category.festival': 'Festival',
    'category.deportes': 'Esportes',
    'category.teatro': 'Teatro',
    'category.danza': 'Dança',
    'category.comedia': 'Comédia',
    
    // Event Titles (dynamic translations)
    'event.title.1': 'Rock Fest 2025 - Os Melhores Artistas do Rock',
    'event.title.2': 'Festival de Música Eletrônica 2025',
    'event.title.3': 'Final de Basquete - Campeonato Nacional',
    'event.title.4': 'O Fantasma da Ópera - Apresentação Especial',
    'event.title.5': 'Concerto Sinfônico - Beethoven Ao Vivo',
    'event.title.6': 'Stand Up Comedy Night',
    'event.title.7': 'Futebol: Clássico Nacional',
    'event.title.8': 'Peça de Teatro: Romeu e Julieta',
    'event.title.9': 'Jazz Night - Lendas do Jazz',
    'event.title.10': 'Boxe: Campeonato Mundial dos Pesos Pesados',
    'event.title.11': 'Balé Folclórico Internacional',
    'event.title.12': 'Festival Gastronômico Internacional',
    'event.title.13': 'Exposição de Arte Contemporânea',
    'event.title.14': 'Tênis: ATP Tour Finals',
    'event.title.15': 'Tour Pop Latino 2025',
    'event.title.16': 'Cirque du Soleil - Alegría',
    'event.title.17': 'Indie Rock Festival USA',
    'event.title.18': 'Musical: O Rei Leão',
    'event.title.19': 'Reggaeton & Trap Party',
    'event.title.20': 'Luta Livre - Evento Principal',
    
    // HomePage
    'home.hero.title': 'Tudo Começa com um Sim',
    'home.hero.subtitle': 'Esse momento em que você decide sair, viver, sentir algo diferente.',
    'home.hero.button': 'Ver mais',
    'home.section2.title': 'Luzes acesas, a multidão vibra',
    'home.section2.subtitle': 'Seu lugar está reservado... e te espera.',
    'home.section3.title': 'O rugido do estádio, antes do gol',
    'home.section3.subtitle': 'Cada ingresso te leva direto ao coração do jogo.',
    'home.section4.title': 'Você ri, você chora, você aplaude.',
    'home.section4.subtitle': 'Porque a arte também se vive por dentro',
    'home.stats.tickets': 'Ingressos Vendidos',
    'home.stats.rating': 'Classificação Média',
    'home.categories.title': 'Explorar por Categoria',
    'home.categories.subtitle': 'Encontre eventos que te emocionam',
    'home.upcoming.subtitle': 'Não perca estes eventos incríveis',
    'home.featured.subtitle': 'Os eventos mais populares agora',
    'home.events.badge': 'Mais de 10.000 eventos disponíveis',
    
    // EventsListPage
    'events.hero.title': 'Viva a experiência dos seus eventos favoritos',
    'events.hero.subtitle': 'Milhares de eventos, tudo em um só lugar. Compre seus ingressos de forma segura e rápida.',
    'events.search.placeholder': 'Buscar eventos, artistas, times...',
    'events.search.cities': 'Todas as cidades',
    'events.search.button': 'Buscar Eventos',
    'events.categories.concerts': 'Concertos',
    'events.categories.sports': 'Esportes',
    'events.categories.theater': 'Teatro',
    'events.categories.festivals': 'Festivais',
    'events.stats.users': 'Usuários Ativos',
    'events.stats.tickets': 'Ingressos Vendidos',
    'events.stats.events': 'Eventos Realizados',
    'events.stats.rating': 'Classificação Média',
    'events.featured.title': 'Eventos em Destaque',
    'events.upcoming.title': 'Próximos eventos',
    'events.upcoming.subtitle': 'Não perca estes eventos incríveis',
    'events.button.buy': 'Comprar ingressos',
    'events.button.viewAll': 'Ver todos os eventos',
    'events.category.eventsCount': 'eventos',
    'events.card.from': 'A partir de',
    'events.card.lastTickets': 'Últimos',
    'events.card.upcoming': 'Próximos',
    'events.card.future': 'Futuros',
    'events.card.current': 'Atuais',
    'events.card.featured': 'Imperdível',
    'events.card.featuredAlt': 'Destaque',
    'events.card.recommended': 'Recomendado',
    'events.card.trending': 'Em alta',
    'events.card.soldOut': 'Esgotado',
    
    // AllEventsPage
    'allevents.back': 'Voltar',
    'allevents.title': 'Todos os Eventos',
    'allevents.filters': 'Filtros',
    'allevents.search.placeholder': 'Buscar eventos...',
    'allevents.categories.all': 'Todos',
    'allevents.sort.date': 'Data',
    'allevents.sort.priceAsc': 'Preço: Menor para Maior',
    'allevents.sort.priceDesc': 'Preço: Maior para Menor',
    'allevents.sort.popularity': 'Popularidade',
    'allevents.sort.name': 'Nome',
    'allevents.sort.by': 'Ordenar por',
    'allevents.filters.advanced': 'Filtros Avançados',
    'allevents.filters.cities': 'Cidades',
    'allevents.filters.price': 'Faixa de Preço',
    'allevents.filters.featured': 'Apenas Destaques',
    'allevents.filters.trending': 'Apenas Tendências',
    'allevents.filters.lastTickets': 'Últimos Ingressos',
    'allevents.pagination.previous': 'Anterior',
    'allevents.pagination.next': 'Próximo',
    'allevents.noResults': 'Nenhum evento encontrado',
    
    // Footer
    'footer.description': 'A melhor plataforma para encontrar e comprar ingressos para seus eventos favoritos.',
    'footer.events': 'Eventos',
    'footer.help': 'Ajuda',
    'footer.help.center': 'Centro de Ajuda',
    'footer.help.contact': 'Contato',
    'footer.help.refund': 'Política de Reembolso',
    'footer.help.terms': 'Termos e Condições',
    'footer.help.privacy': 'Privacidade',
    'footer.organizers': 'Organizadores',
    'footer.organizers.sell': 'Venda Ingressos',
    'footer.organizers.create': 'Criar um Evento',
    'footer.organizers.resources': 'Recursos',
    'footer.organizers.pricing': 'Preços',
    'footer.copyright': 'Todos os direitos reservados.',
    
    // Event Detail
    'event.detail.back': 'Voltar',
    'event.detail.share': 'Compartilhar',
    'event.detail.featured': 'Destaque',
    'event.detail.date': 'Data',
    'event.detail.time': 'Hora',
    'event.detail.location': 'Localização',
    'event.detail.description': 'Descrição do Evento',
    'event.detail.venue': 'Informações do Local',
    'event.detail.venueCapacity': 'Capacidade',
    'event.detail.venueParking': 'Estacionamento',
    'event.detail.venueAccessibility': 'Acessibilidade',
    'event.detail.reviews': 'Avaliações',
    'event.detail.tickets': 'Selecione Seus Ingressos',
    'event.detail.ticketsSubtitle': 'Escolha o tipo de ingresso que preferir',
    'event.detail.ticketAvailable': 'Disponível',
    'event.detail.buyTickets': 'Comprar Ingressos',
    'event.detail.selectTicket': 'Selecione um tipo de ingresso primeiro',
    'event.detail.offer': 'Oferta Especial!',
    'event.detail.offerText': 'Compre 2 ou mais ingressos e ganhe 10% de desconto',
    'event.detail.discount': 'Compre 3 ingressos e ganhe 15% de desconto',
    'event.detail.general': 'Geral',
    'event.detail.vip': 'VIP',
    'event.detail.palco': 'Camarin Premium',
    'event.detail.standard_access': 'Acesso padrão ao evento',
    'event.detail.preferential_seats': 'Assentos preferenciais',
    'event.detail.exclusive_experience': 'Experiência exclusiva',
    'event.detail.general_access': 'Acesso geral',
    'event.detail.parking_included': 'Estacionamento incluído',
    'event.detail.vip_access': 'Acesso à área VIP',
    'event.detail.meet_greet': 'Meet & Greet',
    'event.detail.private_box': 'Camarin privado (4 pessoas)',
    'event.detail.waiter_service': 'Serviço de garçom',
    'event.detail.drinks_included': 'Bebidas incluídas',
    
    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.back': 'Voltar',
    'checkout.event_details': 'Detalhes do Evento',
    'checkout.ticket_type': 'Tipo de Ingresso',
    'checkout.quantity': 'Quantidade de Ingressos',
    'checkout.max_tickets': 'Máximo de 10 ingressos por compra',
    'checkout.buyer_info': 'Informações do Comprador',
    'checkout.buyer_info_desc': 'Precisamos dessas informações para processar sua compra e enviar seus ingressos',
    'checkout.full_name': 'Nome Completo',
    'checkout.email': 'E-mail',
    'checkout.phone': 'Telefone (Opcional)',
    'checkout.attendees': 'Informações dos Participantes',
    'checkout.attendees_desc': 'Digite o nome de cada pessoa que participará do evento',
    'checkout.attendee_name': 'Nome do Participante',
    'checkout.special_requests': 'Solicitações Especiais',
    'checkout.special_requests_placeholder': 'Alergias, necessidades especiais, etc.',
    'checkout.purchase_summary': 'Resumo da Compra',
    'checkout.subtotal': 'Subtotal',
    'checkout.service_fee': 'Taxa de Serviço',
    'checkout.total': 'Total',
    'checkout.pay': 'Pagar',
    'checkout.processing': 'Processando...',
    'checkout.complete_form': 'Complete o formulário acima',
    'checkout.secure_payment': 'Pagamento seguro com seu saldo interno',
    'checkout.insufficient_balance': 'Saldo Insuficiente',
    'checkout.insufficient_balance_desc': 'Você precisa de ${amount} MXN a mais para completar esta compra',
    'checkout.add_balance': 'Adicionar Saldo',
    'checkout.add_balance_title': 'Adicionar Saldo à Sua Conta',
    'checkout.add_balance_desc': 'Selecione o valor que deseja adicionar',
    'checkout.amount': 'Valor',
    'checkout.add': 'Adicionar',
    'checkout.adding': 'Adicionando...',
    'checkout.error.required_fields': 'Por favor, preencha todos os campos obrigatórios',
    'checkout.error.invalid_email': 'Por favor, insira um e-mail válido',
    'checkout.error.attendees': 'Por favor, insira o nome de todos os participantes',
    'checkout.error.complete_steps': 'Por favor, complete todas as etapas antes de fazer o pagamento',
    'checkout.error.buyer_info': 'Por favor, complete as informações do comprador',
    
    // Login
    'login.welcome': 'Bem-vindo ao TicketMaster',
    'login.subtitle': 'Entre ou crie sua conta para continuar',
    'login.password': 'Senha',
    'login.magic_link': 'Magic Link',
    'login.signup': 'Cadastrar',
    'login.passwordless': 'Login sem senha',
    'login.passwordless_desc': 'Receba um link mágico em seu e-mail para acessar instantaneamente',
    'login.email': 'E-mail',
    'login.send_link': 'Enviar Link Mágico ✨',
    'login.sending': 'Enviando...',
    'login.link_sent': 'Link Mágico Enviado! 📧',
    'login.link_sent_desc': 'Enviamos um link de acesso para',
    'login.check_inbox': 'Verifique sua caixa de entrada e clique no link para entrar automaticamente',
    'login.send_another': 'Enviar outro link',
    'login.forgot_password': 'Esqueceu sua senha?',
    'login.sign_in': 'Entrar',
    'login.signing_in': 'Entrando...',
    'login.create_account': 'Criar Conta',
    'login.creating': 'Criando...',
    'login.error.signin': 'Erro ao entrar',
    'login.error.signup': 'Erro ao criar conta',
    'login.error.magic_link': 'Erro ao enviar link mágico',
    'login.error.reset': 'Erro ao enviar link de recuperação',
    
    // Profile
    'profile.back': 'Voltar ao início',
    'profile.my_tickets': 'Meus Ingressos',
    'profile.my_tickets_page': 'Meus Ingressos',
    'profile.my_tickets_desc': 'Ver e baixar todos os seus ingressos de eventos',
    'profile.view_my_tickets': 'Ver Meus Ingressos',
    'profile.transactions': 'Histórico de Transações',
    'profile.loading_tickets': 'Carregando ingressos...',
    'profile.no_tickets': 'Você não tem ingressos',
    'profile.no_tickets_desc': 'Explore eventos e compre seus primeiros ingressos',
    'profile.seat': 'Assento',
    'profile.view_qr': 'Ver QR',
    'profile.transfer': 'Transferir',
    'profile.transferred': 'Recebido por transferência',
    'profile.no_transactions': 'Ainda não há transações',
    'profile.used_tickets': 'Ingressos Usados',
    'profile.used_on': 'Usado em',
    'profile.completed': 'Concluído',
    'profile.transfer_ticket': 'Transferir Ingresso',
    'profile.transfer_desc': 'Digite o endereço de e-mail da pessoa para quem deseja transferir este ingresso',
    'profile.recipient_email': 'E-mail do Destinatário',
    'profile.transferring': 'Transferindo...',
    'profile.important': 'Importante',
    'profile.transfer_warning': 'Uma vez transferido, você não poderá recuperar este ingresso. A pessoa que o receber será a nova proprietária.',
    'profile.verification_code': 'Código de verificação gerado',
    'profile.close': 'Fechar',
    
    // Wallet
    'wallet.title': 'Minha Carteira',
    'wallet.total_balance': 'Saldo Total',
    'wallet.multi_currency': 'Saldo em Diferentes Moedas',
    'wallet.recent_transactions': 'Transações Recentes',
    'wallet.add_balance': 'Adicionar Saldo',
    'wallet.info': 'Informação',
    'wallet.info_desc': 'Seu saldo está protegido e disponível a qualquer momento para comprar ingressos.',
    
    // Cart
    'cart.title': 'Meu Carrinho',
    'cart.empty': 'Carrinho vazio',
    'cart.empty_title': 'Seu carrinho está vazio',
    'cart.empty_desc': 'Adicione ingressos de eventos incríveis ao seu carrinho para começar.',
    'cart.item': 'item',
    'cart.items': 'itens',
    'cart.quantity': 'Quantidade',
    'cart.each': 'cada',
    'cart.summary': 'Resumo do Pedido',
    'cart.subtotal': 'Subtotal',
    'cart.service_fee': 'Taxa de Serviço',
    'cart.total': 'Total',
    'cart.checkout': 'Finalizar Compra',
    'cart.clear': 'Limpar Carrinho',
    'cart.browse_events': 'Explorar Eventos',
    'cart.login_required': 'Faça login para ver seu carrinho',
    'cart.login_required_desc': 'Você precisa fazer login para adicionar ingressos ao seu carrinho.',
    'cart.secure_checkout': 'Pagamento seguro e protegido',
    
    // Confirmation
    'confirmation.success': 'Compra Bem-sucedida!',
    'confirmation.success_desc': 'Seu{plural} {count} ingresso{plural} foi{plural_verb} comprado{plural} com sucesso',
    'confirmation.purchase_summary': 'Resumo da Compra',
    'confirmation.total_paid': 'Total Pago',
    'confirmation.internal_balance': 'Saldo Interno',
    'confirmation.remaining_balance': 'Saldo Restante',
    'confirmation.your_tickets': 'Seus Ingressos',
    'confirmation.your_ticket': 'Seu Ingresso',
    'confirmation.ticket_info': 'Os ingressos estão disponíveis na seção "Meus Ingressos"',
    'confirmation.view_tickets': 'Ver Meus Ingressos',
    
    // Events List
    'events.back': 'Voltar',
    'events.title': 'Explorar Eventos',
    'events.date': 'Data',
    'events.price_low': 'Preço: Menor para Maior',
    'events.price_high': 'Preço: Maior para Menor',
    'events.name': 'Nome A-Z',
    'events.price_range': 'Faixa de Preço',
    'events.special_types': 'Tipos Especiais',
    'events.featured': 'Eventos em Destaque',
    'events.trending': 'Em alta',
    'events.trending_desc': 'Mais populares agora',
    'events.last_tickets': 'Últimos Ingressos',
    'events.no_results': 'Nenhum evento encontrado',
    'events.no_results_desc': 'Tente ajustar seus filtros de pesquisa para obter mais resultados',
    
    // Footer
    'footer.description': 'A melhor plataforma para encontrar e comprar ingressos dos seus eventos favoritos.',
    'footer.events': 'Eventos',
    'footer.sell_tickets': 'Vender Ingressos',
    'footer.create_event': 'Criar um Evento',
    
    // Common UI
    'ui.search': 'Pesquisar Eventos',
    'ui.trending': 'Em alta',
    'ui.last_tickets': 'Últimos',
    'ui.featured': 'Destaque',
    'ui.sold_out': 'ESGOTADO',
    'ui.from': 'A partir de',
    'ui.mis_tickets': 'Meus Ingressos',
    'ui.ingresar': 'Entrar',
    
    // Contact Page
    'contact.page.title': 'Contato',
    'contact.page.description': 'Entre em contato conosco. Estamos aqui para ajudar.',
    'contact.hero.title': 'Estamos Aqui para Ajudar',
    'contact.hero.subtitle': 'Tem dúvidas, sugestões ou precisa de ajuda? Nossa equipe está pronta para atendê-lo.',
    'contact.info.email': 'E-mail',
    'contact.info.phone': 'Telefone',
    'contact.info.location': 'Localização',
    'contact.info.address': 'Av. Principal 123, Cidade, País',
    'contact.info.hours': 'Horário de Atendimento',
    'contact.info.hours.weekdays': 'Seg - Sex: 9:00 - 18:00',
    'contact.info.hours.weekends': 'Sáb - Dom: 10:00 - 16:00',
    'contact.faq.title': 'Precisa de Ajuda Rápida?',
    'contact.faq.description': 'Consulte nossas perguntas frequentes para respostas imediatas.',
    'contact.faq.button': 'Ver Perguntas Frequentes',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.subtitle': 'Preencha o formulário e entraremos em contato o mais breve possível.',
    'contact.form.name': 'Nome Completo',
    'contact.form.name.placeholder': 'Seu nome',
    'contact.form.email': 'E-mail',
    'contact.form.email.placeholder': 'voce@email.com',
    'contact.form.phone': 'Telefone',
    'contact.form.phone.placeholder': '+1 (234) 567-890',
    'contact.form.subject': 'Assunto',
    'contact.form.subject.placeholder': 'Como podemos ajudar?',
    'contact.form.message': 'Mensagem',
    'contact.form.message.placeholder': 'Escreva sua mensagem aqui...',
    'contact.form.submit': 'Enviar Mensagem',
    'contact.form.sending': 'Enviando...',
    'contact.form.required': '* Campos obrigatórios',
    'contact.form.success.title': 'Mensagem Enviada!',
    'contact.form.success.message': 'Obrigado por entrar em contato. Responderemos em breve.',
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
}

// Función para obtener el idioma inicial (siempre español por defecto)
const getInitialLanguage = (): Language => {
  if (typeof window === 'undefined') return 'es';
  
  // FORZAR ESPAÑOL POR DEFECTO - Descomentar la siguiente línea si quieres resetear siempre a español
  // if (typeof window !== 'undefined') localStorage.removeItem('language-storage');
  
  try {
    const stored = localStorage.getItem('language-storage');
    if (stored) {
      const parsed = JSON.parse(stored);
      const savedLang = parsed.state?.language;
      console.log('Language loaded from storage:', savedLang);
      return savedLang || 'es';
    }
  } catch (error) {
    console.warn('Error loading language from storage:', error);
  }
  
  console.log('No language in storage, defaulting to: es');
  return 'es'; // Siempre español por defecto
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: getInitialLanguage(),
      
      setLanguage: (language) => {
        console.log('🌐 Idioma cambiado a:', language);
        set({ language });
      },
    }),
    {
      name: 'language-storage',
      // Verificar que localStorage esté disponible (SSR safe)
      storage: typeof window !== 'undefined' ? localStorage : undefined,
    }
  )
);

